### ISSUE TITLE
Missing support for packages using ssh address

### ISSUE THREAD

**Issue by racinmat** [JuliaRegistries/TagBot#151]
Context: In our company we have private registry, and self-hosted TagBot, and we use ssh keys for authentication for our self-hosted github.
Problem: TagBot does not see packages using ssh address as registered.
In our registry, for packages we have e.g.
`Package.toml` in the registry
```toml
name = "InternalPackage"
uuid = "a2c437b0-bf6b-41a1-8a62-162a814afa99"
repo = "git@git.our_company.com:our_org/InternalPackage.jl.git"
```
and because of https://github.com/JuliaRegistries/TagBot/blob/v1.9.1/tagbot/action/repo.py#L254 it misses the package. 
Should I send a PR to fix it?
