### ISSUE TITLE
How to use it with private registry?

### ISSUE THREAD

**Issue by sairus7** [JuliaRegistries/TagBot#290]
I have a github org with private registry and I'm registering new package versions manually with LocalRegistry:
```
using LocalRegistry
register(package)
```

Now I'm lacking automatic git tag and github releases bound to each new version. 

So I've added TagBot to my package but it didn't work. Seems like TagBot relies on Registrator github app. Should I enable it for my private registry and switch to it to register new versions?

**Comment by terasakisatoshi** [comment]
Hi, @sairus7 

This section [Custom Registries](https://github.com/JuliaRegistries/TagBot#custom-registries) might be helpful?

```yml
name: TagBot
...
...<Omission >
...
jobs:
  TagBot:
    if: github.event_name == 'workflow_dispatch' || github.actor == 'JuliaTagBot'
    runs-on: ubuntu-latest
    steps:
      - uses: JuliaRegistries/TagBot@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ssh: ${{ secrets.DOCUMENTER_KEY }} # required to add tags
          registry: MyOrg/MyRegistry
          registry_ssh: ${{ secrets.REGISTRY_SSH_KEY }} # required to pull/clone MyOrg/MyRegistry
```
