### ISSUE TITLE
Issue with custom registry

### ISSUE THREAD

**Issue by crstnbr** [JuliaRegistries/TagBot#33]
I have a custom registry ([TrebstRegistry](https://github.com/crstnbr/TrebstRegistry)) and am trying to enable TagBot for a package registered therein ([TestPackage2.jl](https://github.com/crstnbr/TestPackage2.jl)).

My [TagBot.yml workflow](https://github.com/crstnbr/TestPackage2.jl/blob/master/.github/workflows/TagBot.yml) looks like this:

```yml
name: TagBot
on:
  schedule:
    - cron: 0 * * * *
jobs:
  TagBot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: JuliaRegistries/TagBot@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          registry: https://github.com/crstnbr/TrebstRegistry
```
Note the extra `registry` entry which I added as explained in the TagBot readme.

However, when this workflow runs, I get an error:
> fatal: empty string is not a valid pathspec. please use . instead if you meant to match all paths

Check yourself here: https://github.com/crstnbr/TestPackage2.jl/commit/c3a932d42f94c3a592ee2e9c1b0f7d7c15c4bb17/checks?check_suite_id=303890250

I don't know how to debug this. Is this a TagBot issue, one with my registry, or just me wrongly setting up things?

Any help is very much appreciated!
Carsten
